build:
  environment:
    php: 8.0

  nodes:
    analysis:
      project_setup:
        override:
          - 'true'

      tests:
        override:
          - php-scrutinizer-run
          - command: vendor/bin/phpunit --coverage-clover=coverage.xml
            coverage:
              file: coverage.xml
              format: clover
          - make ci

    tests: true

checks:
  php: true

filter:
  excluded_paths:
    - 'tests/*'
    - 'examples/*'
