build:
  environment:
    php: 7.1.6

  nodes:
    analysis:
      project_setup:
        override:
          - 'true'

      tests:
        override:
          - php-scrutinizer-run
          - command: phpcs-run
          - command: 'vendor/bin/phpunit --coverage-clover=coverage.xml'
            coverage:
              file: 'coverage.xml'
              format: 'clover'
          - 'vendor/bin/grumphp run --no-interaction'

    tests: true

checks:
  php: true

filter:
  excluded_paths:
    - 'tests/*'
    - 'examples/*'